import logging
import uuid
from pathlib import Path
from typing import Optional

from relation_normalizer import RelationNormalizer
from entity_resolution.entity_resolver import EntityResolver

from graph_storage.connection import Neo4jConnection
from graph_storage.graph_loader import Neo4jGraphLoader


logger = logging.getLogger(__name__)


PROJECT_ROOT = (Path(__file__).resolve().parent)


DEFAULT_SCHEMA_PATH = (
    PROJECT_ROOT
    / "schema_registry.json"
)


class KnowledgeGraphPipeline:
    """
    MVP Knowledge Graph storage pipeline.

    Flow:

        Raw LLM JSON
            ↓
        RelationNormalizer
            ↓

        [Schema Evolution - future]

            ↓
        EntityResolver
            ↓
        Neo4jGraphLoader
            ↓
        Neo4j

    The Neo4j graph contains only
    the latest processed document.
    """

    def __init__(self,schema_path: str | Path = (DEFAULT_SCHEMA_PATH),
                 connection: Optional[Neo4jConnection] = None):

        self.schema_path = (Path(schema_path).resolve())


        # ---------------------------------------------
        # Connection ownership
        # ---------------------------------------------

        if connection is None:

            self.connection = (Neo4jConnection())

            self._owns_connection = True

        else:

            self.connection = connection

            self._owns_connection = False


        # ---------------------------------------------
        # Pipeline components
        # ---------------------------------------------

        self.normalizer = (RelationNormalizer(schema_path=str(self.schema_path)))


        self.resolver = (EntityResolver())


        self.loader = (
            Neo4jGraphLoader(
                connection=self.connection,
                schema_path=self.schema_path,
            )
        )


    # =========================================================
    # Context manager
    # =========================================================

    def __enter__(self):

        return self


    def __exit__(self, exc_type, exc_value,دtraceback):

        self.close()


    # =========================================================
    # Document identity
    # =========================================================

    @staticmethod
    def generate_document_id() -> str:
        """
        Generate a random application-level document ID.

        Example:

            doc_58d0b63f6c14444cba61...
        """

        return (
            "doc_"
            + uuid.uuid4().hex
        )


    # =========================================================
    # Main pipeline
    # =========================================================

    def process_extraction(self, raw_data: dict, document_id: str | None = None) -> dict:
        """
        Process one LLM extraction result.

        Parameters
        ----------
        raw_data:
            Raw JSON returned by the relation
            extraction LLM.

        document_id:
            ID generated by the application when
            the user submitted the document.

            If omitted, Pipeline generates one.

        Returns
        -------
        dict:
            document_id
            normalized_data
            resolved_data
            storage_result
        """

        # ---------------------------------------------
        # Basic pipeline-boundary validation
        # ---------------------------------------------

        if not isinstance(raw_data, dict):

            raise TypeError("raw_data must be a dictionary.")


        # ---------------------------------------------
        # Document ID
        # ---------------------------------------------

        if document_id is None:

            document_id = (self.generate_document_id())


        if (
            not isinstance(document_id, str)
            or not document_id.strip()
        ):

            raise ValueError(
                "document_id must be "
                "a non-empty string."
            )


        document_id = (
            document_id.strip()
        )


        try:

            # =================================================
            # 1. Relation Normalization
            # =================================================

            normalized_data = (
                self.normalizer.normalize(
                    raw_data=raw_data,
                    document_id=document_id,
                )
            )


            # =================================================
            # 2. Schema Evolution
            # =================================================
            #
            # NOT IMPLEMENTED YET.
            #
            # Later:
            #
            # normalized_data = (
            #     self.schema_evolution.process(
            #         normalized_data
            #     )
            # )
            #
            # It belongs HERE:
            #
            # Normalizer
            #     ↓
            # Schema Evolution
            #     ↓
            # Entity Resolver
            #


            # =================================================
            # 3. Entity Resolution
            # =================================================

            resolved_data = (
                self.resolver.resolve(
                    normalized_data
                )
            )


            # =================================================
            # 4. Neo4j Storage
            # =================================================

            storage_result = (
                self.loader.replace_document(
                    resolved_data
                )
            )


            # =================================================
            # Result
            # =================================================

            return {

                "document_id":
                    document_id,

                # Keeping intermediates is useful
                # during MVP debugging.
                "normalized_data":
                    normalized_data,

                "resolved_data":
                    resolved_data,

                "storage_result":
                    storage_result,
            }


        except Exception:

            logger.exception(
                "Knowledge graph pipeline failed "
                "for document_id=%s",
                document_id,
            )

            # Do NOT swallow pipeline errors.
            raise


    # =========================================================
    # Cleanup
    # =========================================================

    def close(self):

        if (
            self._owns_connection
            and self.connection is not None
        ):

            self.connection.close()

            self.connection = None