import json
import logging
import os

from dataclasses import dataclass
from pathlib import Path
from typing import Any

import httpx

from langchain_core.exceptions import ModelError
from langchain_core.output_parsers import StrOutputParser
from langchain_google_genai import ChatGoogleGenerativeAI

from langchain_neo4j.chains.graph_qa.cypher_utils import (
    CypherQueryCorrector,
    Schema,
)

from neo4j import GraphDatabase
from neo4j.exceptions import Neo4jError
from neo4j.graph import (
    Node,
    Path as Neo4jPath,
    Relationship,
)

from neo4j_graphrag.exceptions import (
    Text2CypherRetrievalError,
)
from neo4j_graphrag.retrievers import (
    Text2CypherRetriever,
)
from neo4j_graphrag.retrievers.text2cypher import (
    extract_cypher,
)
from neo4j_graphrag.schema import (
    format_schema,
    get_structured_schema,
)

from .prompts import (
    CYPHER_PROMPT,
    QA_PROMPT,
)


logger = logging.getLogger(__name__)


# ============================================================
# Paths
# ============================================================

PROJECT_ROOT = (
    Path(__file__)
    .resolve()
    .parent
    .parent
)

DEFAULT_CONFIG_PATH = (
    PROJECT_ROOT
    / "config"
    / "text2cypher_config.json"
)

DEFAULT_NEO4J_CONFIG_PATH = (
    PROJECT_ROOT
    / "config"
    / "neo4j_config.json"
)


# ============================================================
# Exceptions
# ============================================================

class GeminiServiceError(RuntimeError):
    """All configured Gemini models failed."""


class CypherDirectionError(ValueError):
    """Generated Cypher does not match graph relationship directions."""


# ============================================================
# Simple LLM response expected by Text2CypherRetriever
# ============================================================

@dataclass
class _TextResponse:
    content: str


# ============================================================
# Adapter
#
# Text2CypherRetriever generates the Cypher itself.
#
# This small adapter only adds:
#   - relationship direction correction
#   - generated Cypher tracking
#   - model tracking
#
# It does NOT execute Cypher.
# ============================================================

class _CypherLLMAdapter:

    def __init__(
        self,
        llm,
        output_parser: StrOutputParser,
    ):
        self.llm = llm
        self.output_parser = output_parser

        self.corrector = None

        self.last_raw_cypher = None
        self.last_cypher = None
        self.last_model = None


    def set_corrector(
        self,
        corrector: CypherQueryCorrector,
    ) -> None:

        self.corrector = corrector


    def invoke(
        self,
        prompt: str,
    ) -> _TextResponse:

        response = self.llm.invoke(
            prompt
        )

        text = self.output_parser.invoke(
            response
        ).strip()

        cypher = extract_cypher(
            text
        ).strip()

        self.last_raw_cypher = cypher
        self.last_model = self._model_name(
            response
        )

        # Use LangChain's existing relationship
        # direction corrector.
        if self.corrector is not None:

            corrected = self.corrector(
                cypher
            )

            if not corrected:

                self.last_cypher = cypher

                raise CypherDirectionError(
                    "Generated Cypher does not match "
                    "the relationship directions "
                    "defined in the current graph schema."
                )

            cypher = corrected

        self.last_cypher = cypher

        logger.debug(
            "Cypher generated by model=%s query=%s",
            self.last_model,
            cypher,
        )

        return _TextResponse(
            content=cypher
        )


    @staticmethod
    def _model_name(
        response,
    ) -> str | None:

        metadata = (
            getattr(
                response,
                "response_metadata",
                None,
            )
            or {}
        )

        return (
            metadata.get("model_name")
            or metadata.get("model")
        )


# ============================================================
# Pipeline
# ============================================================

class Text2CypherPipeline:

    FALLBACK_ANSWER = (
        "نمی‌دانم. اطلاعاتی ندارم!"
    )

    TECHNICAL_NODE_PROPERTIES = {
        "document_id",
        "entity_key",
    }


    # ========================================================
    # Init
    # ========================================================

    def __init__(
        self,
        config_path=DEFAULT_CONFIG_PATH,
        neo4j_config_path=DEFAULT_NEO4J_CONFIG_PATH,
    ):

        self.config = self._load_json(
            config_path
        )

        neo4j_config = self._load_json(
            neo4j_config_path
        )

        self.max_attempts = int(
            self.config.get(
                "max_cypher_attempts",
                6,
            )
        )

        self.max_rows = int(
            self.config.get(
                "max_rows",
                50,
            )
        )

        self.query_timeout = float(
            self.config.get(
                "query_timeout_seconds",
                10,
            )
        )

        if self.max_attempts < 1:
            raise ValueError(
                "max_cypher_attempts must be >= 1."
            )

        if self.max_rows < 1:
            raise ValueError(
                "max_rows must be >= 1."
            )

        self._configure_proxy()

        # --------------------------------------------
        # Gemini + fallback models
        # --------------------------------------------

        self.cypher_model = self._build_llm(
            primary_key="cypher_primary_model",
            fallback_key="cypher_fallback_models",
        )

        self.answer_model = self._build_llm(
            primary_key="answer_primary_model",
            fallback_key="answer_fallback_models",
        )

        self.output_parser = (
            StrOutputParser()
        )

        # --------------------------------------------
        # Neo4j
        # --------------------------------------------

        self.database = (
            neo4j_config.get(
                "database",
                "neo4j",
            )
        )

        self.driver = GraphDatabase.driver(
            neo4j_config["uri"],
            auth=(
                neo4j_config["username"],
                neo4j_config["password"],
            ),
        )

        # --------------------------------------------
        # Adapter used by Text2CypherRetriever
        # --------------------------------------------

        self.cypher_llm = (
            _CypherLLMAdapter(
                llm=self.cypher_model,
                output_parser=self.output_parser,
            )
        )

        self.retriever = None

        # Debug-only internal information.
        # Public ask() response remains unchanged.
        self.last_cypher_model = None
        self.last_answer_model = None


    # ========================================================
    # Context manager
    # ========================================================

    def __enter__(self):
        return self


    def __exit__(
        self,
        exc_type,
        exc_value,
        traceback,
    ):
        self.close()


    # ========================================================
    # Public API
    # ========================================================

    def ask(
        self,
        question: str,
    ) -> dict[str, Any]:

        if (
            not isinstance(question, str)
            or not question.strip()
        ):
            raise ValueError(
                "question must be a non-empty string."
            )

        question = question.strip()

        # --------------------------------------------
        # Refresh real runtime schema.
        # Rebuild retriever because ingest may have
        # replaced the active document.
        # --------------------------------------------

        if not self._refresh_retriever():

            return self._failure_result(
                attempts=0,
                errors=[
                    "Neo4j graph is empty."
                ],
            )

        errors: list[str] = []

        failed_cypher = ""
        error_message = ""

        last_cypher = None

        # ====================================================
        # Generate -> validate -> execute
        #
        # Text2CypherRetriever performs those operations.
        #
        # On a repairable failure we call it again with:
        #
        # failed_cypher + error_message
        # ====================================================

        for attempt in range(
            1,
            self.max_attempts + 1,
        ):

            try:

                result = (
                    self.retriever
                    .get_search_results(
                        query_text=question,
                        prompt_params={
                            "failed_cypher": (
                                failed_cypher
                            ),
                            "error_message": (
                                error_message
                            ),
                            "max_rows": (
                                self.max_rows
                            ),
                        },
                    )
                )

                metadata = (
                    result.metadata
                    or {}
                )

                cypher = (
                    metadata.get("cypher")
                    or self.cypher_llm.last_cypher
                )

                last_cypher = cypher

                self.last_cypher_model = (
                    self.cypher_llm.last_model
                )

                raw_records = (
                    result.records
                )

                truncated = (
                    len(raw_records)
                    > self.max_rows
                )

                raw_records = raw_records[
                    :self.max_rows
                ]

                rows = self._to_jsonable(
                    [
                        record.data()
                        for record
                        in raw_records
                    ]
                )

                # ------------------------------------
                # Same previous behavior:
                #
                # valid query + zero rows
                # is NOT repaired.
                # ------------------------------------

                if not rows:

                    return {
                        "ok": True,
                        "answer": (
                            self.FALLBACK_ANSWER
                        ),
                        "cypher": cypher,
                        "attempts": attempt,
                        "rows": [],
                        "evidence": [],
                        "errors": errors,
                        "truncated": False,
                    }

                answer = (
                    self._generate_answer(
                        question=question,
                        rows=rows,
                    )
                )

                logger.info(
                    "Text2Cypher models: "
                    "cypher=%s answer=%s",
                    self.last_cypher_model,
                    self.last_answer_model,
                )

                return {
                    "ok": True,
                    "answer": answer,
                    "cypher": cypher,
                    "attempts": attempt,
                    "rows": rows,
                    "evidence": (
                        self._collect_evidence(
                            rows
                        )
                    ),
                    "errors": errors,
                    "truncated": truncated,
                }

            # ----------------------------------------
            # Direction correction rejected query.
            # ----------------------------------------

            except CypherDirectionError as exc:

                last_cypher = (
                    self.cypher_llm.last_raw_cypher
                    or last_cypher
                )

                repair = self._prepare_retry(
                    attempt=attempt,
                    cypher=last_cypher,
                    exc=exc,
                    errors=errors,
                )

                if repair is None:

                    return self._failure_result(
                        attempts=attempt,
                        cypher=last_cypher,
                        errors=errors,
                    )

                (
                    failed_cypher,
                    error_message,
                ) = repair

            # ----------------------------------------
            # Text2CypherRetriever failure:
            #
            # - invalid Cypher syntax
            # - non-read-only query
            # ----------------------------------------

            except Text2CypherRetrievalError as exc:

                last_cypher = (
                    self.cypher_llm.last_cypher
                    or self.cypher_llm.last_raw_cypher
                    or last_cypher
                )

                repair = self._prepare_retry(
                    attempt=attempt,
                    cypher=last_cypher,
                    exc=exc,
                    errors=errors,
                )

                if repair is None:

                    return self._failure_result(
                        attempts=attempt,
                        cypher=last_cypher,
                        errors=errors,
                    )

                (
                    failed_cypher,
                    error_message,
                ) = repair

            # ----------------------------------------
            # Neo4j errors not wrapped by Retriever.
            # ----------------------------------------

            except Neo4jError as exc:

                if self._is_retryable_neo4j_error(
                    exc
                ):
                    raise

                if not self._is_repairable_neo4j_error(
                    exc
                ):
                    raise

                last_cypher = (
                    self.cypher_llm.last_cypher
                    or self.cypher_llm.last_raw_cypher
                    or last_cypher
                )

                repair = self._prepare_retry(
                    attempt=attempt,
                    cypher=last_cypher,
                    exc=exc,
                    errors=errors,
                )

                if repair is None:

                    return self._failure_result(
                        attempts=attempt,
                        cypher=last_cypher,
                        errors=errors,
                    )

                (
                    failed_cypher,
                    error_message,
                ) = repair

            # ----------------------------------------
            # Gemini/provider/network failure.
            #
            # Do NOT send application/provider errors
            # to the Cypher repair loop.
            # ----------------------------------------

            except (
                ModelError,
                httpx.TransportError,
            ) as exc:

                raise GeminiServiceError(
                    "All configured Gemini models failed."
                ) from exc

            # ----------------------------------------
            # Python/application bug.
            # ----------------------------------------

            except Exception:

                logger.exception(
                    "Non-Cypher error inside "
                    "Text2Cypher pipeline."
                )

                raise

        return self._failure_result(
            attempts=self.max_attempts,
            cypher=last_cypher,
            errors=errors,
        )


    # ========================================================
    # Runtime Schema + Retriever
    # ========================================================

    def _refresh_retriever(
        self,
    ) -> bool:

        # Neo4j GraphRAG + APOC handle schema discovery.
        structured_schema = (
            get_structured_schema(
                driver=self.driver,
                database=self.database,
                timeout=self.query_timeout,
                is_enhanced=False,
            )
        )

        if not structured_schema.get(
            "node_props"
        ):
            return False

        # Preserve previous behavior:
        # internal storage fields are hidden
        # from the Text2Cypher LLM.
        for properties in (
            structured_schema.get(
                "node_props",
                {},
            ).values()
        ):

            properties[:] = [
                item
                for item in properties
                if item.get("property")
                not in (
                    self.TECHNICAL_NODE_PROPERTIES
                )
            ]

        schema_text = format_schema(
            schema=structured_schema,
            is_enhanced=False,
        )

        # --------------------------------------------
        # Build LangChain's existing relationship
        # direction corrector from runtime schema.
        # --------------------------------------------

        direction_schema = [
            Schema(
                relation["start"],
                relation["type"],
                relation["end"],
            )
            for relation
            in structured_schema.get(
                "relationships",
                [],
            )
        ]

        self.cypher_llm.set_corrector(
            CypherQueryCorrector(
                direction_schema
            )
        )

        # --------------------------------------------
        # Official Neo4j Text2CypherRetriever
        # --------------------------------------------

        self.retriever = (
            Text2CypherRetriever(
                driver=self.driver,
                llm=self.cypher_llm,
                neo4j_schema=schema_text,
                custom_prompt=CYPHER_PROMPT,
                neo4j_database=self.database,
            )
        )

        return True


    # ========================================================
    # Repair loop helper
    # ========================================================

    def _prepare_retry(
        self,
        *,
        attempt: int,
        cypher: str | None,
        exc: Exception,
        errors: list[str],
    ) -> tuple[str, str] | None:

        message = (
            f"{type(exc).__name__}: {exc}"
        )

        errors.append(
            message
        )

        logger.warning(
            "Cypher attempt %s/%s failed. "
            "Query=%r Error=%s",
            attempt,
            self.max_attempts,
            cypher,
            message,
        )

        if attempt >= self.max_attempts:
            return None

        return (
            cypher or "",
            message,
        )


    # ========================================================
    # Answer generation
    # ========================================================

    def _generate_answer(
        self,
        *,
        question: str,
        rows: list[dict[str, Any]],
    ) -> str:

        prompt = QA_PROMPT.format(
            question=question,
            context=json.dumps(
                rows,
                ensure_ascii=False,
                default=str,
            ),
        )

        try:

            response = self.answer_model.invoke(prompt)

        except (
            ModelError,
            httpx.TransportError,
        ) as exc:

            raise GeminiServiceError(
                "All configured Gemini models failed "
                "during answer generation."
            ) from exc

        self.last_answer_model = (
            self._response_model_name(
                response
            )
        )

        answer = (
            self.output_parser
            .invoke(response)
            .strip()
        )

        return (
            answer
            or self.FALLBACK_ANSWER
        )


    # ========================================================
    # Gemini primary + fallback
    # ========================================================
    
    def _build_llm(
        self,
        *,
        primary_key: str,
        fallback_key: str,
    ):
        api_key = (
            self.config.get("api_key")
            or os.getenv("GEMINI_API_KEY")
            or os.getenv("GOOGLE_API_KEY")
        )

        if not api_key:
            raise ValueError(
                "Gemini API key is not configured."
            )

        primary_model = self.config.get(
            primary_key
        )

        fallback_models = self.config.get(
            fallback_key,
            [],
        )

        if (
            not isinstance(primary_model, str)
            or not primary_model.strip()
        ):
            raise ValueError(
                f"{primary_key} must be a non-empty string."
            )

        if not isinstance(
            fallback_models,
            list,
        ):
            raise ValueError(
                f"{fallback_key} must be a list."
            )

        model_names = []

        for name in [
            primary_model,
            *fallback_models,
        ]:
            if (
                isinstance(name, str)
                and name.strip()
                and name.strip() not in model_names
            ):
                model_names.append(
                    name.strip()
                )

        max_retries = int(
            self.config.get(
                "llm_max_retries",
                1,
            )
        )

        max_output_tokens = int(
            self.config.get(
                "llm_max_output_tokens",
                2048,
            )
        )

        models = [
            ChatGoogleGenerativeAI(
                model=model_name,
                api_key=api_key,
                max_retries=max_retries,
                max_output_tokens=max_output_tokens,
            )
            for model_name in model_names
        ]

        if len(models) == 1:
            return models[0]

        return models[0].with_fallbacks(
            models[1:],
            exceptions_to_handle=(
                ModelError,
                httpx.TransportError,
            ),
        )
    # def _build_llm(
    #     self,
    # ):

    #     api_key = (
    #         self.config.get("api_key")
    #         or os.getenv(
    #             "GEMINI_API_KEY"
    #         )
    #         or os.getenv(
    #             "GOOGLE_API_KEY"
    #         )
    #     )

    #     if not api_key:
    #         raise ValueError(
    #             "Gemini API key is not configured."
    #         )

    #     primary_model = (
    #         self.config.get(
    #             "primary_model",
    #             "gemini-3.5-flash",
    #         )
    #     )

    #     fallback_models = (
    #         self.config.get(
    #             "fallback_models",
    #             [],
    #         )
    #     )

    #     if not isinstance(
    #         fallback_models,
    #         list,
    #     ):
    #         raise ValueError(
    #             "fallback_models must be a list."
    #         )

    #     model_names = []

    #     for name in [
    #         primary_model,
    #         *fallback_models,
    #     ]:

    #         if (
    #             isinstance(name, str)
    #             and name.strip()
    #             and name.strip()
    #             not in model_names
    #         ):

    #             model_names.append(
    #                 name.strip()
    #             )

    #     if not model_names:
    #         raise ValueError(
    #             "At least one Gemini model "
    #             "must be configured."
    #         )

    #     max_retries = int(
    #         self.config.get(
    #             "llm_max_retries",
    #             1,
    #         )
    #     )

    #     max_output_tokens = int(
    #         self.config.get(
    #             "llm_max_output_tokens",
    #             2048,
    #         )
    #     )

    #     models = [
    #         ChatGoogleGenerativeAI(
    #             model=model_name,
    #             api_key=api_key,
    #             max_retries=max_retries,
    #             max_output_tokens=(
    #                 max_output_tokens
    #             ),
    #         )
    #         for model_name
    #         in model_names
    #     ]

    #     if len(models) == 1:
    #         return models[0]

    #     return models[0].with_fallbacks(
    #         models[1:],
    #         exceptions_to_handle=(
    #             ModelError,
    #             httpx.TransportError,
    #         ),
    #     )


    # ========================================================
    # Evidence
    # ========================================================

    @classmethod
    def _collect_evidence(
        cls,
        value: Any,
    ) -> list[str]:

        evidence = []

        def walk(
            item: Any,
        ) -> None:

            if isinstance(
                item,
                dict,
            ):

                for key, child in (
                    item.items()
                ):

                    if (
                        str(key).lower()
                        == "evidence"
                        and isinstance(
                            child,
                            str,
                        )
                        and child.strip()
                    ):

                        if child not in evidence:

                            evidence.append(
                                child
                            )

                    else:

                        walk(
                            child
                        )

            elif isinstance(
                item,
                list,
            ):

                for child in item:

                    walk(
                        child
                    )

        walk(
            value
        )

        return evidence


    # ========================================================
    # Neo4j -> JSON safe
    # ========================================================

    @classmethod
    def _to_jsonable(
        cls,
        value: Any,
    ) -> Any:

        if (
            value is None
            or isinstance(
                value,
                (
                    str,
                    int,
                    float,
                    bool,
                ),
            )
        ):
            return value

        if isinstance(
            value,
            Node,
        ):

            return {
                "labels": list(
                    value.labels
                ),
                "properties": {
                    key: cls._to_jsonable(
                        item
                    )
                    for key, item
                    in dict(value).items()
                },
            }

        if isinstance(
            value,
            Relationship,
        ):

            return {
                "type": (
                    type(value).__name__
                ),
                "properties": {
                    key: cls._to_jsonable(
                        item
                    )
                    for key, item
                    in dict(value).items()
                },
            }

        if isinstance(
            value,
            Neo4jPath,
        ):

            return {
                "nodes": [
                    cls._to_jsonable(
                        node
                    )
                    for node
                    in value.nodes
                ],
                "relationships": [
                    cls._to_jsonable(
                        relationship
                    )
                    for relationship
                    in value.relationships
                ],
            }

        if isinstance(
            value,
            dict,
        ):

            return {
                str(key): cls._to_jsonable(
                    item
                )
                for key, item
                in value.items()
            }

        if isinstance(
            value,
            (
                list,
                tuple,
                set,
            ),
        ):

            return [
                cls._to_jsonable(
                    item
                )
                for item
                in value
            ]

        return str(
            value
        )


    # ========================================================
    # Neo4j error classification
    # ========================================================

    @staticmethod
    def _is_retryable_neo4j_error(
        exc: Neo4jError,
    ) -> bool:

        checker = getattr(
            exc,
            "is_retryable",
            None,
        )

        if callable(
            checker
        ):
            return bool(
                checker()
            )

        return False


    @staticmethod
    def _is_repairable_neo4j_error(
        exc: Neo4jError,
    ) -> bool:

        code = (
            getattr(
                exc,
                "code",
                "",
            )
            or ""
        )

        return (
            ".Statement."
            in code
        )


    # ========================================================
    # Debug metadata
    # ========================================================

    @staticmethod
    def _response_model_name(
        response,
    ) -> str | None:

        metadata = (
            getattr(
                response,
                "response_metadata",
                None,
            )
            or {}
        )

        return (
            metadata.get(
                "model_name"
            )
            or metadata.get(
                "model"
            )
        )


    # ========================================================
    # Proxy
    # ========================================================

    def _configure_proxy(
        self,
    ) -> None:

        proxy = self.config.get(
            "proxy"
        )

        if not proxy:
            return

        os.environ[
            "HTTPS_PROXY"
        ] = proxy

        os.environ[
            "HTTP_PROXY"
        ] = proxy


    # ========================================================
    # Response helpers
    # ========================================================

    def _failure_result(
        self,
        *,
        attempts: int,
        errors: list[str],
        cypher: str | None = None,
    ) -> dict[str, Any]:

        return {
            "ok": False,
            "answer": (
                self.FALLBACK_ANSWER
            ),
            "cypher": cypher,
            "attempts": attempts,
            "rows": [],
            "evidence": [],
            "errors": errors,
            "truncated": False,
        }


    # ========================================================
    # Config
    # ========================================================

    @staticmethod
    def _load_json(
        path,
    ) -> dict[str, Any]:

        path = Path(
            path
        )

        if not path.exists():

            raise FileNotFoundError(
                f"Configuration file "
                f"not found: {path}"
            )

        with path.open(
            "r",
            encoding="utf-8",
        ) as file:

            data = json.load(
                file
            )

        if not isinstance(
            data,
            dict,
        ):

            raise ValueError(
                "Configuration must be "
                f"a JSON object: {path}"
            )

        return data


    # ========================================================
    # Cleanup
    # ========================================================

    def close(
        self,
    ) -> None:

        if getattr(
            self,
            "driver",
            None,
        ) is not None:

            self.driver.close()
            self.driver = None

